'use client'

import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertCircle,
  Box,
  Brain,
  Briefcase,
  Bug,
  Cpu,
  Code2,
  Cloud,
  Database,
  Globe,
  Key,
  Layers,
  Layout,
  Lightbulb,
  LineChart,
  Lock,
  Mail,
  Monitor,
  PenTool,
  RefreshCw,
  Rocket,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Target,
  Terminal,
  Wrench,
  Zap,
  Workflow,
  GitBranch,
  FileCode,
  FolderCog,
  Bot,
  MessageSquare,
  BarChart3,
  Palette,
  Settings,
  Package,
  Network,
  Mic,
  Image,
  FileJson,
  Container,
  Blocks,
  Binary,
  BookOpen,
  CheckCircle2,
  CircleDot,
  ClipboardList,
  Cog,
  Compass,
  Copy,
  MousePointer,
  Download,
  Eye,
  Filter,
  FolderOpen,
  Gauge,
  Grid3X3,
  HardDrive,
  Headphones,
  Hexagon,
  Infinity,
  Link2,
  List,
  Loader2,
  Map,
  Megaphone,
  PieChart,
  Plug,
  Puzzle,
  Search,
  Share2,
  Sliders,
  Star,
  Stethoscope,
  Store,
  Table,
  Timer,
  TrendingUp,
  Upload,
  UserCheck,
  Users,
  Video,
  Webhook,
} from 'lucide-react'

export interface ServiceIconEntry {
  key: string
  Icon: LucideIcon
}

/** Free Lucide icon library for service icons. Key is stored in DB; use same key on frontend to render. */
const RAW_SERVICE_ICON_LIBRARY: ServiceIconEntry[] = [
  { key: 'activity', Icon: Activity },
  { key: 'alert-circle', Icon: AlertCircle },
  { key: 'api', Icon: Link2 },
  { key: 'bar-chart', Icon: BarChart3 },
  { key: 'binary', Icon: Binary },
  { key: 'blocks', Icon: Blocks },
  { key: 'book-open', Icon: BookOpen },
  { key: 'bot', Icon: Bot },
  { key: 'box', Icon: Box },
  { key: 'brain', Icon: Brain },
  { key: 'briefcase', Icon: Briefcase },
  { key: 'bug', Icon: Bug },
  { key: 'check-circle', Icon: CheckCircle2 },
  { key: 'circle-dot', Icon: CircleDot },
  { key: 'clipboard-list', Icon: ClipboardList },
  { key: 'cloud', Icon: Cloud },
  { key: 'cog', Icon: Cog },
  { key: 'code2', Icon: Code2 },
  { key: 'compass', Icon: Compass },
  { key: 'container', Icon: Container },
  { key: 'copy', Icon: Copy },
  { key: 'cpu', Icon: Cpu },
  { key: 'cursor-click', Icon: MousePointer },
  { key: 'database', Icon: Database },
  { key: 'download', Icon: Download },
  { key: 'eye', Icon: Eye },
  { key: 'file-code', Icon: FileCode },
  { key: 'file-json', Icon: FileJson },
  { key: 'filter', Icon: Filter },
  { key: 'folder-cog', Icon: FolderCog },
  { key: 'folder-open', Icon: FolderOpen },
  { key: 'gauge', Icon: Gauge },
  { key: 'git-branch', Icon: GitBranch },
  { key: 'globe', Icon: Globe },
  { key: 'grid', Icon: Grid3X3 },
  { key: 'hard-drive', Icon: HardDrive },
  { key: 'headphones', Icon: Headphones },
  { key: 'hexagon', Icon: Hexagon },
  { key: 'infinity', Icon: Infinity },
  { key: 'image', Icon: Image },
  { key: 'key', Icon: Key },
  { key: 'layers', Icon: Layers },
  { key: 'layout', Icon: Layout },
  { key: 'lightbulb', Icon: Lightbulb },
  { key: 'line-chart', Icon: LineChart },
  { key: 'link2', Icon: Link2 },
  { key: 'list', Icon: List },
  { key: 'loader', Icon: Loader2 },
  { key: 'lock', Icon: Lock },
  { key: 'mail', Icon: Mail },
  { key: 'map', Icon: Map },
  { key: 'megaphone', Icon: Megaphone },
  { key: 'message-square', Icon: MessageSquare },
  { key: 'mic', Icon: Mic },
  { key: 'monitor', Icon: Monitor },
  { key: 'mouse-pointer', Icon: MousePointer },
  { key: 'network', Icon: Network },
  { key: 'package', Icon: Package },
  { key: 'palette', Icon: Palette },
  { key: 'pen-tool', Icon: PenTool },
  { key: 'pie-chart', Icon: PieChart },
  { key: 'plug', Icon: Plug },
  { key: 'puzzle', Icon: Puzzle },
  { key: 'refresh-cw', Icon: RefreshCw },
  { key: 'rocket', Icon: Rocket },
  { key: 'search', Icon: Search },
  { key: 'server', Icon: Server },
  { key: 'settings', Icon: Settings },
  { key: 'share2', Icon: Share2 },
  { key: 'shield', Icon: Shield },
  { key: 'sliders', Icon: Sliders },
  { key: 'smartphone', Icon: Smartphone },
  { key: 'sparkles', Icon: Sparkles },
  { key: 'star', Icon: Star },
  { key: 'stethoscope', Icon: Stethoscope },
  { key: 'store', Icon: Store },
  { key: 'table', Icon: Table },
  { key: 'target', Icon: Target },
  { key: 'terminal', Icon: Terminal },
  { key: 'timer', Icon: Timer },
  { key: 'trending-up', Icon: TrendingUp },
  { key: 'upload', Icon: Upload },
  { key: 'user-check', Icon: UserCheck },
  { key: 'users', Icon: Users },
  { key: 'video', Icon: Video },
  { key: 'webhook', Icon: Webhook },
  { key: 'workflow', Icon: Workflow },
  { key: 'wrench', Icon: Wrench },
  { key: 'zap', Icon: Zap },
]

/** Filter out any icons that failed to import (undefined in older Lucide versions). */
export const SERVICE_ICON_LIBRARY: ServiceIconEntry[] = RAW_SERVICE_ICON_LIBRARY.filter(
  (e) => e.Icon != null
)

/** Keys for backwards compatibility (e.g. "ai" -> "brain", "fullstack" -> "layers") */
export const SERVICE_ICON_ALIASES: Record<string, string> = {
  ai: 'brain',
  web: 'globe',
  fullstack: 'layers',
  intelligence: 'sparkles',
  software: 'code2',
  backend: 'server',
  frontend: 'monitor',
  modernization: 'refresh-cw',
  automation: 'zap',
  consulting: 'briefcase',
  design: 'palette',
  mobile: 'smartphone',
  code: 'code2',
}

export function resolveServiceIconKey(key: string | null | undefined): string | null {
  if (!key || !key.trim()) return null
  const k = key.toLowerCase().trim().replace(/\s+/g, '-')
  return SERVICE_ICON_ALIASES[k] ?? k
}

export function getServiceIconComponent(key: string | null | undefined): LucideIcon | null {
  const resolved = resolveServiceIconKey(key)
  if (!resolved) return null
  const entry = SERVICE_ICON_LIBRARY.find((e) => e.key === resolved)
  return entry?.Icon ?? null
}
